# Generated by Django 5.2.5 on 2025-10-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amout_paid',
            new_name='amount_paid',
        ),
    ]
